[package]
name = "chip8-vm"
version = "0.1.0"
authors = ["N0ps32 <benjamin@raeder.technology>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chip8 = { path = "chip8" }

[workspace]
members = [
    "chip8",
]